---
pid: tmp/pids/thin.pid
timeout: 30
wait: 30
log: log/thin.log
max_conns: 1024
require: []

environment: staging
max_persistent_conns: 512
servers: 2
daemonize: true
chdir: /var/www/beta.oiga.me/current

socket: /tmp/thin.staging.sock
